---
# main yml file to perform binary installation of infinidb

# Establish homedir for idbuser; to be referenced by tasks
# running as root or as nonroot.
- hosts: infinidb_nodes
  tasks:
  - set_fact: homedir={{ ansible_env.HOME }}
  - set_fact: idbbasedir="/usr/local"
    when:     idbuser == 'root'
  - set_fact: idbbasedir={{ homedir }}
    when:     idbuser != 'root'

- hosts: infinidb_nodes
# if this is nonroot installation, we need to sudo to
# root to perform most of the preinstall tasks.
  sudo:  '{{ sudo_flag }}'
  sudo_user: root
  roles:
    - binpreinstall

- hosts: '{{ pm1_host }}'
  roles:
    - bininstall
